---
# L2VNI for rack-1
apiVersion: openpe.openperouter.github.io/v1alpha1
kind: L2VNI
metadata:
  name: storage-rack-1
  namespace: openperouter-system
spec:
  nodeSelector:
    matchLabels:
      topology.kubernetes.io/rack: rack-1
  vni: 10200
  vrf: storage
  hostmaster:
    type: linux-bridge
    linuxBridge:
      name: br-storage
  l2gatewayips:
    - 10.200.1.1/24
---
# L2VNI for rack-2
apiVersion: openpe.openperouter.github.io/v1alpha1
kind: L2VNI
metadata:
  name: storage-rack-2
  namespace: openperouter-system
spec:
  nodeSelector:
    matchLabels:
      topology.kubernetes.io/rack: rack-2
  vni: 10201
  vrf: storage
  hostmaster:
    type: linux-bridge
    linuxBridge:
      name: br-storage
  l2gatewayips:
    - 10.200.2.1/24

